In [24]:
import numpy as np 
import pandas as pd 
import seaborn as sb
import matplotlib.pyplot as plt

In [25]:
data=pd.read_csv('../Datas/ww-ii-data.csv')
data.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_3348\2230128585.py:1: DtypeWarning: Columns (7,8,18,25) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('../Datas/ww-ii-data.csv')


STA      Date Precip  WindGustSpd    MaxTemp    MinTemp   MeanTemp  \
0  10001  7/1/1942  1.016          NaN  25.555556  22.222222  23.888889   
1  10001  7/2/1942      0          NaN  28.888889  21.666667  25.555556   
2  10001  7/3/1942   2.54          NaN  26.111111  22.222222  24.444444   
3  10001  7/4/1942   2.54          NaN  26.666667  22.222222  24.444444   
4  10001  7/5/1942      0          NaN  26.666667  21.666667  24.444444   

  Snowfall PoorWeather  YR  ...  FB  FTI ITH  PGT  TSHDSBRSGF  SD3  RHX  RHN  \
0      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
1      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
2      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
3      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
4      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   

  RVG  WTE  
0 NaN  NaN  
1 NaN  NaN  
2 NaN  NaN  
3 NaN  NaN  
4 NaN  NaN  

[5 rows x 31 columns]

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119040 entries, 0 to 119039
Data columns (total 31 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   STA          119040 non-null  int64  
 1   Date         119040 non-null  object 
 2   Precip       119040 non-null  object 
 3   WindGustSpd  532 non-null     float64
 4   MaxTemp      119040 non-null  float64
 5   MinTemp      119040 non-null  float64
 6   MeanTemp     119040 non-null  float64
 7   Snowfall     117877 non-null  object 
 8   PoorWeather  34237 non-null   object 
 9   YR           119040 non-null  int64  
 10  MO           119040 non-null  int64  
 11  DA           119040 non-null  int64  
 12  PRCP         117108 non-null  object 
 13  DR           533 non-null     float64
 14  SPD          532 non-null     float64
 15  MAX          118566 non-null  float64
 16  MIN          118572 non-null  float64
 17  MEA          118542 non-null  float64
 18  SNF          117877 non-

In [27]:
data.isna().sum()

STA                 0
Date                0
Precip              0
WindGustSpd    118508
MaxTemp             0
MinTemp             0
MeanTemp            0
Snowfall         1163
PoorWeather     84803
YR                  0
MO                  0
DA                  0
PRCP             1932
DR             118507
SPD            118508
MAX               474
MIN               468
MEA               498
SNF              1163
SND            113477
FT             119040
FB             119040
FTI            119040
ITH            119040
PGT            118515
TSHDSBRSGF      84803
SD3            119040
RHX            119040
RHN            119040
RVG            119040
WTE            119040
dtype: int64

In [28]:
data=data.fillna(data.mean())

C:\Users\hp\AppData\Local\Temp\ipykernel_3348\2490576204.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data=data.fillna(data.mean())


In [29]:
data.isnull().sum()

STA                 0
Date                0
Precip              0
WindGustSpd         0
MaxTemp             0
MinTemp             0
MeanTemp            0
Snowfall         1163
PoorWeather     84803
YR                  0
MO                  0
DA                  0
PRCP             1932
DR                  0
SPD                 0
MAX                 0
MIN                 0
MEA                 0
SNF              1163
SND                 0
FT             119040
FB             119040
FTI            119040
ITH            119040
PGT                 0
TSHDSBRSGF      84803
SD3            119040
RHX            119040
RHN            119040
RVG            119040
WTE            119040
dtype: int64

In [37]:
data['Snowfall'].unique()

array([0.0, nan, '0', '22.86', '33.02', '30.48', '2.54', '5.08', '10.16',
       '7.62', '20.32', '15.24', '17.78', '12.7', '25.4', '27.94',
       '43.18', '38.1', '45.72', '53.34', '58.42', '66.04', '76.2',
       '81.28', '73.66', '63.5', '50.8', '48.26', '60.96', '55.88',
       '35.56', '78.74', '40.64', '86.36', '83.82', '68.58', '#VALUE!',
       10.16, 7.62, 15.24, 2.54, 5.08, 12.7], dtype=object)

In [43]:
data['Snowfall']=pd.to_numeric(data['Snowfall'],errors='coerce')

In [45]:
data['Snowfall'].unique()

array([ 0.  ,   nan, 22.86, 33.02, 30.48,  2.54,  5.08, 10.16,  7.62,
       20.32, 15.24, 17.78, 12.7 , 25.4 , 27.94, 43.18, 38.1 , 45.72,
       53.34, 58.42, 66.04, 76.2 , 81.28, 73.66, 63.5 , 50.8 , 48.26,
       60.96, 55.88, 35.56, 78.74, 40.64, 86.36, 83.82, 68.58])

In [46]:
data['Snowfall']=data['Snowfall'].fillna(data.mean())

C:\Users\hp\AppData\Local\Temp\ipykernel_3348\1038393649.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data['Snowfall']=data['Snowfall'].fillna(data.mean())


In [48]:
data['Snowfall'].unique()

array([ 0.  ,   nan, 22.86, 33.02, 30.48,  2.54,  5.08, 10.16,  7.62,
       20.32, 15.24, 17.78, 12.7 , 25.4 , 27.94, 43.18, 38.1 , 45.72,
       53.34, 58.42, 66.04, 76.2 , 81.28, 73.66, 63.5 , 50.8 , 48.26,
       60.96, 55.88, 35.56, 78.74, 40.64, 86.36, 83.82, 68.58])

In [49]:
data=data.dropna(axis=1)

In [50]:
data.isnull().sum()

STA            0
Date           0
Precip         0
WindGustSpd    0
MaxTemp        0
MinTemp        0
MeanTemp       0
YR             0
MO             0
DA             0
DR             0
SPD            0
MAX            0
MIN            0
MEA            0
SND            0
PGT            0
dtype: int64

In [51]:
x=data[['STA','YR','MO','DA']]
y=data['MaxTemp']

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=3243) 

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [55]:
LR.predict([X_test.iloc[150]])###Temperature in 150 days

c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([29.1528231])

In [56]:
y_pred=LR.predict(X_test)

In [57]:
from sklearn.metrics import mean_absolute_error

In [58]:
mean_absolute_error(y_test,y_pred)

5.839875078654816

In [59]:
data.describe()

STA    WindGustSpd        MaxTemp        MinTemp  \
count  119040.000000  119040.000000  119040.000000  119040.000000   
mean    29659.435795      37.774534      27.045111      17.789511   
std     20953.209402       0.687777       8.717817       8.334572   
min     10001.000000      18.520000     -33.333333     -38.333333   
25%     11801.000000      37.774534      25.555556      15.000000   
50%     22508.000000      37.774534      29.444444      21.111111   
75%     33501.000000      37.774534      31.666667      23.333333   
max     82506.000000      75.932000      50.000000      34.444444   

            MeanTemp             YR             MO             DA  \
count  119040.000000  119040.000000  119040.000000  119040.000000   
mean       22.411631      43.805284       6.726016      15.797530   
std         8.297982       1.136718       3.425561       8.794541   
min       -35.555556      40.000000       1.000000       1.000000   
25%        20.555556      43.000000       4.000000       8.000000   
50%        25.555556      44.000000       7.000000      16.000000   
75%        27.222222      45.000000      10.000000      23.000000   
max        40.000000      45.000000      12.000000      31.000000   

                  DR            SPD            MAX            MIN  \
count  119040.000000  119040.000000  119040.000000  119040.000000   
mean       26.998124      20.396617      81.003745      64.273808   
std         1.017596       0.371370      14.839727      14.453003   
min         2.000000      10.000000     -28.000000     -37.000000   
25%        26.998124      20.396617      78.000000      59.000000   
50%        26.998124      20.396617      85.000000      70.000000   
75%        26.998124      20.396617      89.000000      74.000000   
max        78.000000      41.000000     122.000000      94.000000   

                 MEA       SND            PGT  
count  119040.000000  119040.0  119040.000000  
mean       72.644843       0.0      12.085333  
std        14.181324       0.0       0.380256  
min       -32.000000       0.0       0.000000  
25%        69.000000       0.0      12.085333  
50%        78.000000       0.0      12.085333  
75%        81.000000       0.0      12.085333  
max       104.000000       0.0      23.900000

In [60]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.010647719355518337

In [64]:
X=data[['STA','WindGustSpd','YR','MO','DA','SPD','MAX','MIN','MEA','SND','PGT','MeanTemp','MinTemp']]
y=data['MaxTemp']

In [65]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=3243) 

In [66]:
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [67]:
y_pred=LR.predict(X_test)
mean_absolute_error(y_test,y_pred)

0.04067527565226579

In [68]:
r2_score(y_test,y_pred)

0.995537109705923